version: "3.3"

x-common:
  &common
  build:     
    context: .
    dockerfile: ./Dockerfile # Dockerfile we created for Airflow in order to install our requirements.txt
  env_file:
    - .env 
  volumes:
    - ./notebooks:/opt/spark-apps
    - ./delta:/opt/spark-data

services:
  spark-master:
    <<: *common
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    <<: *common
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
  